
Insert into csedb.ies (ID_IES,nome) values (8,'SECID SOC EDU CIDADE DE SÃO PAULO');
Insert into csedb.ies (ID_IES,nome) values (9,'SECID SOC EDU CIDADE DE SÃO PAULO');
Insert into csedb.ies (ID_IES,nome) values (13,'ACEF S/A');
Insert into csedb.ies (ID_IES,nome) values (2,'CRUZEIRO DO SUL EDUCACIONAL S.A.');
Insert into csedb.ies (ID_IES,nome) values (1,'CRUZEIRO DO SUL EDUCACIONAL S.A.');
Insert into csedb.ies (ID_IES,nome) values (3,'CRUZEIRO DO SUL EDUCACIONAL S.A.');
Insert into csedb.ies (ID_IES,nome) values (4,'SOC. EMPR. DE ENS. SUPERIOR DO LITORAL NORTE LTDA');
Insert into csedb.ies (ID_IES,nome) values (5,'CRUZEIRO DO SUL EDUCACIONAL S.A.');
Insert into csedb.ies (ID_IES,nome) values (6,'CENTRO DE ENSINO UNIFICADO DO DISTRITO FEDERAL');
Insert into csedb.ies (ID_IES,nome) values (11,'SECID SOC EDU CIDADE DE SÃO PAULO');
Insert into csedb.ies (ID_IES,nome) values (7,'CRUZEIRO DO SUL EDUCACIONAL S.A.');
Insert into csedb.ies (ID_IES,nome) values (12,'CRUZEIRO DO SUL EDUCACIONAL S.A.');
Insert into csedb.ies (ID_IES,nome) values (10,'SECID SOC EDU CIDADE DE SÃO PAULO');
Insert into csedb.ies (ID_IES,nome) values (14,'ACEF S/A');
Insert into csedb.ies (ID_IES,nome) values (32,'CENTRO DE ENSINO UNIFICADO DO DISTRITO FEDERAL');
Insert into csedb.ies (ID_IES,nome) values (29,'SOC. DE EDUCAÇÃO NOSSA SENHORA DO PATROCINIO S/S LTDA');
Insert into csedb.ies (ID_IES,nome) values (30,'SOCIEDADE DE EDUCAÇÃO NOSSA SENHORA DO PATROCÍNIO');
Insert into csedb.ies (ID_IES,nome) values (31,'SOCIEDADE DE EDUCAÇÃO NOSSA SENHORA DO PATROCÍNIO');
Insert into csedb.ies (ID_IES,nome) values (33,'SOC. DE EDUCAÇÃO NOSSA SENHORA DO PATROCINIO S/S LTDA');
Insert into csedb.ies (ID_IES,nome) values (22,'ACEF S/A');
Insert into csedb.ies (ID_IES,nome) values (23,'SECID SOC EDU CIDADE DE SÃO PAULO');
Insert into csedb.ies (ID_IES,nome) values (25,'INSTITUTO DE ENSINO SÃO SEBASTIÃO LTDA');
Insert into csedb.ies (ID_IES,nome) values (26,'INSTITUTO DE ENSINO CARAGUÁ LTDA - EPP');
Insert into csedb.ies (ID_IES,nome) values (27,'COLEGIO SÃO SEBASTIÃO - EDUC INFANTIL E ENS. FUND. LTDA');
Insert into csedb.ies (ID_IES,nome) values (16,'CRUZEIRO DO SUL EDUCACIONAL S.A.');
Insert into csedb.ies (ID_IES,nome) values (17,'SOC. EMPR. DE ENS. SUPERIOR DO LITORAL NORTE LTDA');
Insert into csedb.ies (ID_IES,nome) values (18,'CENTRO DE ENSINO UNIFICADO DO DISTRITO FEDERAL');
Insert into csedb.ies (ID_IES,nome) values (19,'SECID SOC EDU CIDADE DE SÃO PAULO');
Insert into csedb.ies (ID_IES,nome) values (15,'ACEF - PÓS-GRADUAÇÃO');
Insert into csedb.ies (ID_IES,nome) values (20,'INSTITUTO FRANCANO DE ENSINO ALTO PADRÃO');
Insert into csedb.ies (ID_IES,nome) values (21,'ACEF - PÓS-GRADUAÇÃO EAD');
Insert into csedb.ies (ID_IES,nome) values (24,'CRUZEIRO DO SUL EDUCACIONAL S.A.');
Insert into csedb.ies (ID_IES,nome) values (28,'INSTITUTO DE ENSINO SÃO SEBASTIÃO LTDA');
Insert into csedb.ies (ID_IES,nome) values (62,'SECID SOC EDU CIDADE DE SÃO PAULO');
Insert into csedb.ies (ID_IES,nome) values (61,'SECID SOC EDU CIDADE DE SÃO PAULO');
Insert into csedb.ies (ID_IES,nome) values (50,'SECID SOC EDU CIDADE DE SÃO PAULO');
Insert into csedb.ies (ID_IES,nome) values (51,'SECID SOC EDU CIDADE DE SÃO PAULO');
Insert into csedb.ies (ID_IES,nome) values (56,'SECID SOC EDU CIDADE DE SÃO PAULO');
Insert into csedb.ies (ID_IES,nome) values (59,'SECID SOC EDU CIDADE DE SÃO PAULO');
Insert into csedb.ies (ID_IES,nome) values (60,'SECID SOC EDU CIDADE DE SÃO PAULO');
